FROM node:12
## WORKDIR specifies the directory our
## application's code will live within
WORKDIR /
## We copy our package.json file to our
## app directory
COPY package*.json ./
## We then run npm install to install
## express for our application
RUN npm install
## We then copy the rest of our application
## to the app direcoty
COPY . .

ENV PORT=4000

EXPOSE 4000
## We start our application by calling
## npm start.
CMD ["npm", "start"]